// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwcdoIz36oooQvQ2RlGwon33iCtmZWB8',
    appId: '1:1044569108940:web:91329f2e4bca547e8b2d69',
    messagingSenderId: '1044569108940',
    projectId: 'hi-task-26519',
    authDomain: 'hi-task-26519.firebaseapp.com',
    storageBucket: 'hi-task-26519.appspot.com',
    measurementId: 'G-EPEL2W3W22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtPjntIalffMLIkV1IgGWoFYOa4ATaivU',
    appId: '1:1044569108940:android:f8147953b5bfe86f8b2d69',
    messagingSenderId: '1044569108940',
    projectId: 'hi-task-26519',
    storageBucket: 'hi-task-26519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-I5Ua3wXWlej6b5YoslncXBbSNP4Tm2c',
    appId: '1:1044569108940:ios:9c7469d2ef7fba1c8b2d69',
    messagingSenderId: '1044569108940',
    projectId: 'hi-task-26519',
    storageBucket: 'hi-task-26519.appspot.com',
    androidClientId: '1044569108940-jevih9u1b1ktk44i967uv6b8mdoh3np4.apps.googleusercontent.com',
    iosClientId: '1044569108940-gt4bk7657gdgd0rchmatthqqkmasl0pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-I5Ua3wXWlej6b5YoslncXBbSNP4Tm2c',
    appId: '1:1044569108940:ios:bbbc1fc955971e598b2d69',
    messagingSenderId: '1044569108940',
    projectId: 'hi-task-26519',
    storageBucket: 'hi-task-26519.appspot.com',
    androidClientId: '1044569108940-jevih9u1b1ktk44i967uv6b8mdoh3np4.apps.googleusercontent.com',
    iosClientId: '1044569108940-9it2p7l12jgccb77vrt3bl7qnmtlb4u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiTask.RunnerTests',
  );
}
